name: Discover & Add Repos via SSH

on:
  workflow_dispatch:

jobs:
  discover-and-add:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Authenticate gh CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh auth status

      - name: Discover all repos from user/org
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo list ferristhiel --limit 200 --json name,sshUrl |
            jq -r '.[] | "\(.name) \(.sshUrl)"' > all_repos.txt
          cat all_repos.txt

      - name: Add submodules for missing repos
        run: |
          touch .gitmodules
          added=false
          while read -r name url; do
            echo "Considering: $name"
            if [[ "$name" == "workspace_test" ]]; then
              echo "  ❌ Skipping self"
              continue
            fi
            if grep -Fq "$name" .gitmodules; then
              echo "  ⏩ Already in .gitmodules"
            else
              echo "  ✅ Adding submodule $name"
              git submodule add --branch main "$url" "$name"
              sed -i "/path = $name/a\\    ignore = all" .gitmodules
              added=true
            fi
          done < all_repos.txt
          echo "added=$added" >> $GITHUB_OUTPUT