name: Clone Private Repos with SSH Deploy Key

on:
  push:
    branches:
      - main

jobs:
  clone-with-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'   # must be string, not comment or boolean

      - name: Setup SSH Agent and add deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add GitHub.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Verify SSH access to GitHub
        run: ssh -T git@github.com || true

      - name: Clone additional private repo (if needed)
        run: |
          git clone git@github.com:your-username/private-repo.git

      # Add your other build/test/deploy steps here