name: Clone Private Repos with SSH Deploy Key

on:
  push:
    branches:
      - main

jobs:
  clone-with-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow=false to allow full git history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If you have submodules:
          submodules: recursive

      - name: Setup SSH Agent and add deploy key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add GitHub.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Verify SSH access
        run: ssh -T git@github.com || true

      - name: Clone additional private repo or submodule if needed
        run: |
          # Example of cloning another private repo with SSH:
          git clone git@github.com:username/private-repo.git
          
          # OR if using submodules, update them explicitly:
          git submodule update --init --recursive

      # Add your other build/test/deploy steps here