name: Discover & Add New Submodules

on:
  schedule:
    - cron: '0 3 * * *'    # daily at 03:00 UTC
  workflow_dispatch: {}    # manual trigger

permissions:
  contents: write          # allow pushing changes

jobs:
  discover-and-add:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Ensure .gitmodules exists
        run: |
          if [ ! -f .gitmodules ]; then
            echo "# Git submodules configuration" > .gitmodules
            git add .gitmodules
            git commit -m "chore: initialize .gitmodules" || echo "nothing to commit"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GH CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Fetch all my repos
        id: list
        run: |
          gh repo list joshuawiebe --limit 200 --json name,sshUrl \
            | jq -r '.[] | "\(.name) \(.sshUrl)"' > all_repos.txt

      - name: Read existing submodules
        id: existing
        run: |
          grep '^\[submodule ' .gitmodules \
            | sed -E 's/\[submodule "(.+)"\]/\1/' > existing.txt || echo "" > existing.txt

      - name: Add any new submodules
        id: add
        run: |
          added=false
          while read -r name url; do
            # Skip the workspace repo itself
            if [[ "$name" == "workspace" ]]; then
              echo "Skipping self: $name"
              continue
            fi
            # Add if missing
            if ! grep -Fxq "$name" existing.txt; then
              echo "Adding submodule: $name"
              git submodule add --branch main "$url" "$name"
              # Inject ignore = all
              sed -i "/path = $name/a\\    ignore = all" .gitmodules
              added=true
            fi
          done < all_repos.txt
          echo "added=$added" >> $GITHUB_OUTPUT

      - name: Sort .gitmodules entries
        if: steps.add.outputs.added == 'true'
        run: |
          awk 'BEGIN{RS=""; ORS="\n\n"} {print}' .gitmodules \
            | sort -t '"' -k2 > .gitmodules.sorted
          mv .gitmodules.sorted .gitmodules

      - name: Commit & push changes
        if: steps.add.outputs.added == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .gitmodules .git/config
          git commit -m "chore: auto-add new submodules and sort entries"
          git push origin main

      - name: No new submodules
        if: steps.add.outputs.added == 'false'
        run: echo "✅ No new repositories to add as submodules."