name: Discover & Add New Submodules via SSH

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  discover-and-add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure .gitmodules exists
        run: |
          if [ ! -f .gitmodules ]; then
            echo "# Git submodules configuration" > .gitmodules
            git add .gitmodules
            git commit -m "chore: initialize .gitmodules" || echo "no changes"
          fi

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add GitHub.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install GH CLI + jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Fetch all repos via GH CLI
        id: list
        run: |
          gh repo list joshuawiebe --limit 200 --json name,sshUrl \
            | jq -r '.[] | "\(.name) \(.sshUrl)"' > all_repos.txt

      - name: Read existing submodules
        id: existing
        run: |
          grep -E '^\[submodule "' .gitmodules | sed -E 's/\[submodule "(.+)".*/\1/' > existing.txt || echo "" > existing.txt

      - name: Add new submodules via SSH
        id: add
        run: |
          added="false"
          while read -r name url; do
            echo "Checking $name..."
            if [ "$name" = "workspace" ] || [ "$name" = "workspace_test" ]; then
              echo "  Skipping self"
              continue
            fi
            if ! grep -Fxq "$name" existing.txt; then
              echo "  Adding submodule: $name"
              git submodule add --branch main "$url" "$name"
              sed -i "/path = $name/a\\    ignore = all" .gitmodules
              added="true"
            else
              echo "  Already exists"
            fi
          done < all_repos.txt
          echo "::set-output name=added::$added"

      - name: Sort .gitmodules entries
        if: steps.add.outputs.added == 'true'
        run: |
          awk 'BEGIN{RS=""; ORS="\n\n"}1' .gitmodules | sort -t '"' -k2 > .gitmodules.sorted
          mv .gitmodules.sorted .gitmodules

      - name: Commit & push changes
        if: steps.add.outputs.added == 'true'
        run: |
          git add .gitmodules
          git commit -m "chore: auto-add new submodules and sort entries"
          git push origin main

      - name: No new submodules
        if: steps.add.outputs.added == 'false'
        run: echo "✅ No new repositories to add as submodules."