name: Discover & Add New Submodules via SSH

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  discover-and-add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup SSH Agent & known_hosts
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure .gitmodules exists
        run: |
          if [ ! -f .gitmodules ]; then
            touch .gitmodules
            git add .gitmodules
            git commit -m "chore: initialize .gitmodules" || echo "nothing to commit"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Fetch all repos via GH CLI
        run: |
          gh repo list joshuawiebe --limit 200 --json name,sshUrl \
            | jq -r '.[] | "\(.name) \(.sshUrl)"' > all_repos.txt
          echo "First 10 repos:"
          head -n 10 all_repos.txt

      - name: Read existing submodules
        run: |
          grep '^\[submodule ' .gitmodules \
            | sed -E 's/\[submodule "(.+)"\]/\1/' > existing.txt || touch existing.txt
          echo "Existing submodules count: $(wc -l < existing.txt)"

      - name: Add new submodules via SSH
        id: add
        run: |
          added=false
          while read -r name url; do
            echo "Checking $name..."
            [[ "$name" =~ workspace ]] && { echo "Skipping workspace root"; continue; }
            if ! grep -Fxq "$name" existing.txt; then
              echo "✅ Adding submodule: $name"
              git submodule add --branch main "$url" "$name" || continue
              sed -i "/path = $name/a\\    ignore = all" .gitmodules
              git add "$name"
              added=true
            else
              echo "➡️ Already tracked: $name"
            fi
          done < all_repos.txt
          echo "added=$added" >> $GITHUB_OUTPUT

      - name: Commit & push changes
        if: steps.add.outputs.added == 'true'
        run: |
          git add .gitmodules */
          git commit -m "chore: auto-add new submodules"
          git push origin main

      - name: Nothing to do
        if: steps.add.outputs.added == 'false'
        run: echo "✅ No new repositories found."